### ISSUE TITLE
`modify` and `modifyOnThread`

### ISSUE THREAD

**Issue by coclique** [iand675/thread-utils#1]
It will be nice if there are functions with the signatures:

```haskell
modify :: MonadIO m => ThreadStorageMap a -> (a -> (a, b)) -> m b
modifyOnThread :: MonadIO m => ThreadStorageMap a -> ThreadId -> (a -> (a, b)) -> m b
```

as the are the most general form of operation derivable from `atomicModifyIORef`.

**Comment by iand675** [comment]
Something like this is now supported: `update` and `updateOnThread` work similarly to this, but they also allow setting/deleting values within the thread storage map.
